### ISSUE TITLE
程序失效

### ISSUE THREAD

**Issue by Maxmumu** [q878740953/OnePlusCloud#1]
由于一加改动网页，程序报错，显示
Traceback (most recent call last):
  File "E:\一加云服务\OnePlusCloud-master\opcloud.py", line 100, in <module>
    op.run()
  File "E:\一加云服务\OnePlusCloud-master\opcloud.py", line 91, in run
    js_data = self.send_request(data)
  File "E:\一加云服务\OnePlusCloud-master\opcloud.py", line 55, in send_request
    response = requests.post(self.url, cookies=self.cookies, data=data, headers=self.headers)
  File "C:\Users\16423\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\16423\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\16423\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\16423\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\16423\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='cloud.h2os.com', port=443): Max retries exceeded with url: /gallery/pc/listNormalPhotos (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))

进程已结束,退出代码1

希望大佬可以再维护一下，我有很多照片存在一加云，万分感激！

**Comment by q878740953** [comment]
一次性工具，使用人数也不多，目前已就业，暂无时间维护
